SAMPLE_EVENTS = [
    {
        "student_id": "S001",
        "timestamp": "2026-06-13T10:00:00",
        "activity_type": "login",
        "duration_minutes": 5,
        "sentiment_score": -0.7,
        "missed_classes": 3,
        "assignment_delay_days": 5,
        "social_interaction_score": 0.2,
    },
    {
        "student_id": "S002",
        "timestamp": "2026-06-13T10:05:00",
        "activity_type": "login",
        "duration_minutes": 45,
        "sentiment_score": 0.6,
        "missed_classes": 0,
        "assignment_delay_days": 0,
        "social_interaction_score": 0.85,
    },
    {
        "student_id": "S003",
        "timestamp": "2026-06-13T10:10:00",
        "activity_type": "login",
        "duration_minutes": 8,
        "sentiment_score": -0.5,
        "missed_classes": 1,
        "assignment_delay_days": 2,
        "social_interaction_score": 0.5,
    },
    {
        "student_id": "S004",
        "timestamp": "2026-06-13T10:15:00",
        "activity_type": "login",
        "duration_minutes": 3,
        "sentiment_score": -0.8,
        "missed_classes": 4,
        "assignment_delay_days": 6,
        "social_interaction_score": 0.15,
    },
    {
        "student_id": "S005",
        "timestamp": "2026-06-13T10:20:00",
        "activity_type": "login",
        "duration_minutes": 12,
        "sentiment_score": 0.3,
        "missed_classes": 5,
        "assignment_delay_days": 4,
        "social_interaction_score": 0.4,
    },
]
